LojaDeGames/Models/Cliente.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LojaDeGames.Models
{
    public class Cliente : Controller
    {
        // GET: Cliente

        [Required(ErrorMessage = "O nome do cliente é obrigatório!")]
        public string ClienteNome { get; set; }

        [StringLength(14, MinimumLength = 10, ErrorMessage = "CPF incompleto ou inválido.")]
        public string ClienteCPF { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd/MM/yyy}", ApplyFormatInEditMode = true)]
        public DateTime ClieDtNasc
        {
            get
            {
                return this.clieDtNasc.HasValue
                    ? this.clieDtNasc.Value
                    : DateTime.Now;
            }
            set
            {
                this.clieDtNasc = value;
            }
        }
        private DateTime? clieDtNasc = null;

        [RegularExpression(@"\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*", ErrorMessage = "Email inválido.")]

        public string ClienteEmail { get; set; }



        public string ClienteCel { get; set; }

        [StringLength(100, MinimumLength = 10, ErrorMessage = "Informe o endereço completo.")]
        public string ClienteEnd { get; set; }
    }
}

LojaDeGames/Models/Funcionario.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LojaDeGames.Models
{
    public class Funcionario : Controller
    {
        // GET: Funcionario
        [Range(1, 10, ErrorMessage = "O código deve ter de 1 a 10 dígitos")]
        public ushort FuncCod { get; set; }

        [Required(ErrorMessage = "O nome do funcionário é obrigatório")]
        public string FuncNome { get; set; }

        [StringLength(14, MinimumLength = 10, ErrorMessage = "CPF incompleto ou inválido.")]
        public string FuncCPF { get; set; }


        [StringLength(12, MinimumLength = 7, ErrorMessage = "RG incompleto ou inválido.")]
        public string FuncRg { get; set; }

        public DateTime FuncDtNasc
        {
            get
            {
                return this.funcDtNasc.HasValue
                    ? this.funcDtNasc.Value
                    : DateTime.Now;
            }
            set
            {
                this.funcDtNasc = value;
            }
        }
        private DateTime? funcDtNasc = null;

        [StringLength(100, MinimumLength = 10, ErrorMessage = "Informe o endereço completo.")]
        public string FuncEnd { get; set; }

        public string FuncCel { get; set; }


        [RegularExpression(@"\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*", ErrorMessage = "Email inválido.")]
        public string FuncEmail { get; set; }


        [StringLength(100, MinimumLength = 3, ErrorMessage = "Informe o cargo a qual exerce.")]
        public string FuncCargo { get; set; }

    }
}

LojaDeGames/Models/Jogo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LojaDeGames.Models
{
    public class Jogo : Controller
    {
        // GET: Jogo
        [Range(1, 10, ErrorMessage = "O código deve ter de 1 a 10 dígitos")]
        public ushort JogoCod { get; set; }
        [Required(ErrorMessage = "O nome é obrigatório")]
        public string JogoNome { get; set; }

        [Required(ErrorMessage = "A versão do jogo é necessária.")]
        public int JogoVersao { get; set; }

        [Required(ErrorMessage = "Insira o desenvolvedor do jogo!")]
        [StringLength(200, MinimumLength = 3, ErrorMessage = "Informe o desenvolvedor com no minímo 3 caracteres a 200.")]
        public string JogoDesenv { get; set; }

        [Required(ErrorMessage = "O gênero do jogo é necessário.")]
        public string JogoGen { get; set; }

        [Range(12, 100, ErrorMessage = "Idade permitida entre 12 a 100 anos!")]
        [Required(ErrorMessage = "Introduza a faixa etária recomendada.")]
        public int JogoFaixaEt { get; set; }


        [Required(ErrorMessage = "Informe a plataforma do jogo.")]
        public string JogoPlat { get; set; }

        [Range(1958, 2021, ErrorMessage = "O ano de lançamento do jogo parte de 1958 a 2021.")]
        [Required(ErrorMessage = "Insira o ano de lançamento do jogo.")]
        public int JogoAnoLanc { get; set; }

        public string JogoSinopse { get; set; }

    }
}

LojaDeGames/Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LojaDeGames.Models;
using LojaDeGames.Repositorio;


namespace LojaDeJogos.Controllers
{
    public class ClienteController : Controller
    {
        // GET: Cliente
        public ActionResult Cliente()
        {
            var cliente = new Cliente(); // aqui criamos o projeto
            return View(cliente); // Retornamos para a view dados
        }
        Ações ac = new Ações();

        [HttpPost]
        public ActionResult CadCliente(Cliente cliente)
        {
            ac.CadastrarClientes(cliente);
            return View(cliente);
        }

        public ActionResult ListarCliente()
        {
            var ExibirClie = new Ações();
            var TodosClie = ExibirClie.ListarCliente();
            return View(TodosClie);
        }
    }
}

LojaDeGames/Controllers/FuncionarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LojaDeGames.Models;
using LojaDeGames.Repositorio;

namespace LojaDeJogos.Controllers
{
    public class FuncionarioController : Controller
    {
        // GET: Funcionario
        public ActionResult Funcionario()
        {
            var funcionario = new Funcionario();
            return View(funcionario);
        }
        Ações ac = new Ações();

        [HttpPost]
        public ActionResult CadFuncionario(Funcionario funcionario)
        {
            ac.CadastrarFuncionario(funcionario);
            return View(funcionario);
        }

        public ActionResult ListarFuncionario()
        {
            var ExibirFunc = new Ações();
            var TodosFunc = ExibirFunc.ListarFuncionario();
            return View(TodosFunc);
        }
    }
}

LojaDeGames/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LojaDeJogos.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

LojaDeGames/Controllers/JogoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LojaDeGames.Models;
using LojaDeGames.Repositorio;

namespace LojaDeJogos.Controllers
{
    public class JogoController : Controller
    {
        // GET: Jogo
        public ActionResult Jogo()
        {
            var jogo = new Jogo(); // aqui criamos o projeto
            return View(jogo); // Retornamos para a view dados
        }
        Ações ac = new Ações();

        [HttpPost]
        public ActionResult CadJogo(Jogo jogo)
        {
            ac.CadastrarJogos(jogo);
            return View(jogo);
        }


        public ActionResult ListarJogo()
        {
            var ExibirJogo = new Ações();
            var TodosJogo = ExibirJogo.ListarJogo();
            return View(TodosJogo);
        }

    }
}

LojaDeGames/Views/Cliente/CadCliente.cshtml
@model LojaDeGames.Models.Cliente

@{
    ViewBag.Title = "CadCliente";
}
<br />

<h2>Dados Cadastrados com sucesso!</h2>
<br />
<p>@Html.ActionLink("Voltar", "Cliente")</p>
<p>@Html.ActionLink("Visualizar Cliente", "ListarCliente")</p>

LojaDeGames/Views/Cliente/Cliente.cshtml
@model  LojaDeGames.Models.Cliente


@{
    ViewBag.Title = "Cliente";
}


<br />

<h2>Cadastro de Clientes</h2>
@using (Html.BeginForm("CadCliente", "Cliente", FormMethod.Post))
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Dados do Cliente</legend>
        <div class="editor-label">
            Nome
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ClienteNome)
            @Html.ValidationMessageFor(model => model.ClienteNome)
        </div>

        <div class="editor-label">
            CPF
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ClienteCPF)
            @Html.ValidationMessageFor(model => model.ClienteCPF)
        </div>

        <div class="editor-label">
            Data de Nascimento
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ClieDtNasc)
            @Html.ValidationMessageFor(model => model.ClieDtNasc)

        </div>

        <div class="editor-label">
            Email
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ClienteEmail)
            @Html.ValidationMessageFor(model => model.ClienteEmail)

        </div>

        <div class="editor-label">
            Número do Celular
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ClienteCel)
            @Html.ValidationMessageFor(model => model.ClienteCel)

        </div>

        <div class=" editor-label">
            Endereço
        </div>
        <div class=" editor-field">
            @Html.EditorFor(model => model.ClienteEnd)
            @Html.ValidationMessageFor(model => model.ClienteEnd)
        </div>
        <br />

        <p><input type="submit" value="Cadastrar" /></p>
    </fieldset>

}

LojaDeGames/Views/Cliente/ClienteResultado.cshtml
@model  LojaDeGames.Models.Cliente


@{
    ViewBag.Title = "ClienteResultado";
}


<br />
<h2>Cliente</h2>
<fieldset>
    <legend>Cadastro Cliente</legend>

    <div class="editor-label">Nome do Cliente:</div>
    <div class="editor-field">@Html.DisplayFor(m => m.ClienteNome)</div> <br />

    <div class="editor-label">CPF do Cliente:</div>
    <div class="editor-field">@Html.DisplayFor(m => m.ClienteCPF) </div> <br />

    <div class="editor-label">Data de Nascimento do Cliente:</div>
    <div class="editor-field">@Html.DisplayFor(m => m.ClieDtNasc)</div> <br />

    <div class="editor-label">Email do Cliente:</div>
    <div class="editor-field">@Html.DisplayFor(m => m.ClienteEmail)</div> <br />

    <div class="editor-label">Número do Celular do Cliente:</div>
    <div class="editor-field">@Html.DisplayFor(m => m.ClienteCel)</div> <br />

    <div class="editor-label">Endereço do Cliente:</div>
    <div class="editor-field">@Html.DisplayFor(m => m.ClienteEnd)</div>


    <br />

    @Html.ActionLink("Voltar", "Index", "Home")

</fieldset>

LojaDeGames/Views/Cliente/ListarCliente.cshtml
@model IEnumerable<LojaDeGames.Models.Cliente>
@{
    ViewBag.Title = "ListarCliente";
}


<br />
<br />
<p>@Html.ActionLink("Cadastrar Cliente", "Cliente")</p>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(m => m.ClienteNome)
        </th>
        <th>
            @Html.DisplayNameFor(m => m.ClienteCPF)
        </th>
        <th>
            @Html.DisplayNameFor(m => m.ClieDtNasc)
        </th>
        <th>
            @Html.DisplayNameFor(m => m.ClienteEmail)
        </th>
        <th>
            @Html.DisplayNameFor(m => m.ClienteCel)
        </th>
        <th>
            @Html.DisplayNameFor(m => m.ClienteEnd)
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ClienteNome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ClienteCPF)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ClieDtNasc)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ClienteEmail)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ClienteCel)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ClienteEnd)
            </td>
            <td>
                @Html.ActionLink("Alterar", "AltCliente", null, new { cdClie = item.ClienteCPF }, new { @class = "btn btn-primary btn-xs" })
                @Html.ActionLink("Deletar", "DelCliente", null, new { cdClie = item.ClienteCPF }, new { @class = "btn btn-danger btn-xs" })
            </td>
        </tr>
    }
</table>

LojaDeGames/Views/Funcionario/CadFuncionario.cshtml
@model LojaDeGames.Models.Funcionario
@{
    ViewBag.Title = "CadFuncionario";
}

<h2>Dados Cadastrados com sucesso!</h2>
<br />
<p>@Html.ActionLink("Voltar", "Funcionario")</p>
<p>@Html.ActionLink("Visualizar Funcionário", "ListarFuncionario")</p>

LojaDeGames/Views/Funcionario/Funcionario.cshtml
@model LojaDeGames.Models.Funcionario

@{
    ViewBag.Title = "Funcionario";
}



<br />
<h2>Cadastro de Funcionários</h2>
@using (Html.BeginForm("CadFuncionario", "Funcionario", FormMethod.Post))
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Dados do Funcionário</legend>
        <div class="editor-label">
            Código
        </div>
        <div class="editor-field">
            @Html.EditorFor(m => m.FuncCod)
            @Html.ValidationMessageFor(m => m.FuncCod)
        </div>

        <div class="editor-label">
            Nome
        </div>
        <div class="editor-field">
            @Html.EditorFor(m => m.FuncNome)
            @Html.ValidationMessageFor(m => m.FuncNome)
        </div>

        <div class="editor-label">
            CPF
        </div>
        <div class="editor-field">
            @Html.EditorFor(m => m.FuncCPF)
            @Html.ValidationMessageFor(m => m.FuncCPF)
        </div>

        <div class="editor-label">
            RG
        </div>
        <div class="editor-field">
            @Html.EditorFor(m => m.FuncRg)
            @Html.ValidationMessageFor(m => m.FuncRg)
        </div>

        <div class="editor-label">
            Data de Nascimento
        </div>
        <div class="editor-field">
            @Html.EditorFor(m => m.FuncDtNasc)
            @Html.ValidationMessageFor(m => m.FuncDtNasc)
        </div>

        <div class="editor-label">
            Endereço
        </div>
        <div class="editor-field">
            @Html.EditorFor(m => m.FuncEnd)
            @Html.ValidationMessageFor(m => m.FuncEnd)
        </div>

        <div class="editor-label">
            Celular
        </div>
        <div class="editor-field">
            @Html.EditorFor(m => m.FuncCel)
            @Html.ValidationMessageFor(m => m.FuncCel)
        </div>

        <div class="editor-label">
            Email
        </div>
        <div class="editor-field">
            @Html.EditorFor(m => m.FuncEmail)
            @Html.ValidationMessageFor(m => m.FuncEmail)
        </div>

        <div class="editor-label">
            Cargo
        </div>
        <div class="editor-field">
            @Html.EditorFor(m => m.FuncCargo)
            @Html.ValidationMessageFor(m => m.FuncCargo)
        </div>

        <br />

        <p><input type="submit" value="Cadastrar" /></p>


    </fieldset>

}

LojaDeGames/Views/Funcionario/FuncionarioResultado.cshtml
@model LojaDeGames.Models.Funcionario


@{
    ViewBag.Title = "FuncionarioResultado";
}


<br />

<h2>Listar</h2>
<fieldset>
    <legend>Lista de Funcionários</legend>

    <div class="editor-label">
        Código do Funcionário:
    </div>
    <div class="editor-field">@Html.DisplayFor(m => m.FuncCod)</div> <br />

    <div class="editor-label">
        Nome do Funcionário:
    </div>
    <div class="editor-field">@Html.DisplayFor(m => m.FuncNome)</div> <br />

    <div class="editor-label">
        CPF do Funcionário:
    </div>
    <div class="editor-field">@Html.DisplayFor(m => m.FuncCPF)</div> <br />

    <div class="editor-label">
        RG do Funcionário:
    </div>
    <div class="editor-field">@Html.DisplayFor(m => m.FuncRg)</div> <br />

    <div class="editor-label">
        Data de Nascimento do Funcionário:
    </div>
    <div class="editor-field">@Html.DisplayFor(m => m.FuncDtNasc)</div> <br />

    <div class="editor-label">
        Endereço do Funcionário:
    </div>
    <div class="editor-field">@Html.DisplayFor(m => m.FuncEnd)</div> <br />

    <div class="editor-label">
        Número do celular do Funcionário:
    </div>
    <div class="editor-field">@Html.DisplayFor(m => m.FuncCel)</div> <br />

    <div class="editor-label">
        Email do Funcionário:
    </div>
    <div class="editor-field">@Html.DisplayFor(m => m.FuncEmail)</div> <br />

    <div class="editor-label">
        Cargo do Funcionário:
    </div>
    <div class="editor-field">@Html.DisplayFor(m => m.FuncCargo)</div>

    <br />

    @Html.ActionLink("Voltar", "Index", "Home")

</fieldset>

LojaDeGames/Views/Funcionario/ListarFuncionario.cshtml
@model IEnumerable<LojaDeGames.Models.Funcionario>

@{
    ViewBag.Title = "ListarFuncionario";
}
<br />
<br />
<p>@Html.ActionLink("Cadastrar Funcionário", "Funcionario")</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(m => m.FuncCod)
        </th>
        <th>
            @Html.DisplayNameFor(m => m.FuncNome)
        </th>
        <th>
            @Html.DisplayNameFor(m => m.FuncCPF)
        </th>
        <th>
            @Html.DisplayNameFor(m => m.FuncRg)
        </th>
        <th>
            @Html.DisplayNameFor(m => m.FuncDtNasc)
        </th>
        <th>
            @Html.DisplayNameFor(m => m.FuncEnd)
        </th>
        <th>
            @Html.DisplayNameFor(m => m.FuncCel)
        </th>
        <th>
            @Html.DisplayNameFor(m => m.FuncEmail)
        </th>
        <th>
            @Html.DisplayNameFor(m => m.FuncCargo)
        </th>

        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FuncCod)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FuncNome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FuncCPF)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FuncRg)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FuncDtNasc)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FuncEnd)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FuncCel)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FuncEmail)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FuncCargo)
            </td>
            <td>
                @Html.ActionLink("Alterar", "AltFuncionario", null, new { cdFunc = item.FuncCod }, new { @class = "btn btn-primary btn-xs" })
                @Html.ActionLink("Deletar", "DelFuncionario", null, new { cdFunc = item.FuncCod }, new { @class = "btn btn-danger btn-xs" })
            </td>
        </tr>
    }
</table>

LojaDeGames/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

LojaDeGames/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

LojaDeGames/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
<br />
<div>
    <h2>Bem-vindo a Gameland</h2>
</div>

LojaDeGames/Views/Jogo/CadJogo.cshtml
@model LojaDeGames.Models.Jogo
@{
    ViewBag.Title = "CadJogo";
}

<h2>CadJogo</h2>
<h2>Dados Cadastrados com sucesso!</h2>
<br />
<p>@Html.ActionLink("Voltar", "Jogo")</p>
<p>@Html.ActionLink("Visualizar Jogos", "ListarJogo")</p>

LojaDeGames/Views/Jogo/JogoResultado.cshtml
@model LojaDeGames.Models.Jogo


@{
    ViewBag.Title = "JogoResultado";
}


<br />
<h2>Jogos</h2>
<fieldset>
    <legend>Lista de Jogos</legend>

    <div class="editor-label">Código do Jogo:</div>
    <div class="editor-field">@Html.DisplayFor(model => model.JogoCod)</div> <br />

    <div class="editor-label">Nome do Jogo:</div>
    <div class="editor-field">@Html.DisplayFor(model => model.JogoNome) </div> <br />

    <div class="editor-label">Versão do Jogo:</div>
    <div class="editor-field">@Html.DisplayFor(model => model.JogoVersao) </div> <br />

    <div class="editor-label">Desenvolvedor do Jogo:</div>
    <div class="editor-field">@Html.DisplayFor(model => model.JogoDesenv)</div> <br />

    <div class="editor-label">Gênero do Jogo:</div>
    <div class="editor-field">@Html.DisplayFor(model => model.JogoGen)</div> <br />

    <div class="editor-label">Faixa Etária Recomendada:</div>
    <div class="editor-field">@Html.DisplayFor(model => model.JogoFaixaEt)</div> <br />

    <div class="editor-label">Plataforma do Jogo:</div>
    <div class="editor-field">@Html.DisplayFor(model => model.JogoPlat)</div> <br />

    <div class="editor-label">Ano de Lançamento do Jogo:</div>
    <div class="editor-field">@Html.DisplayFor(model => model.JogoAnoLanc)</div> <br />

    <div class="editor-label">Sinopse do Jogo:</div>
    <div class="editor-field">@Html.DisplayFor(model => model.JogoSinopse)</div>

    <br />

    @Html.ActionLink("Voltar", "Index", "Home")

</fieldset>

LojaDeGames/Views/Jogo/ListarJogo.cshtml
@model IEnumerable<LojaDeGames.Models.Jogo>
@{
    ViewBag.Title = "ListarJogo";
}
<br />
<br />
<p>@Html.ActionLink("Cadastrar Jogo", "Jogo")</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(m => m.JogoCod)
        </th>
        <th>
            @Html.DisplayNameFor(m => m.JogoNome)
        </th>
        <th>
            @Html.DisplayNameFor(m => m.JogoVersao)
        </th>
        <th>
            @Html.DisplayNameFor(m => m.JogoDesenv)
        </th>
        <th>
            @Html.DisplayNameFor(m => m.JogoGen)
        </th>
        <th>
            @Html.DisplayNameFor(m => m.JogoFaixaEt)
        </th>
        <th>
            @Html.DisplayNameFor(m => m.JogoPlat)
        </th>
        <th>
            @Html.DisplayNameFor(m => m.JogoAnoLanc)
        </th>
        <th>
            @Html.DisplayNameFor(m => m.JogoSinopse)
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.JogoCod)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.JogoNome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.JogoVersao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.JogoDesenv)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.JogoGen)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.JogoFaixaEt)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.JogoPlat)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.JogoAnoLanc)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.JogoSinopse)
            </td>
            <td>
                @Html.ActionLink("Alterar", "AltJogo", null, new { cdJogo = item.JogoCod }, new { @class = "btn btn-primary btn-xs" })
                @Html.ActionLink("Deletar", "DelJogo", null, new { cdJogo = item.JogoCod }, new { @class = "btn btn-danger btn-xs" })
            </td>
        </tr>
    }
</table>

LojaDeGames/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Meu Aplicativo ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("GAMELAND", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Jogo", "Jogo", "Jogo")
                    <li>@Html.ActionLink("Cliente", "Cliente", "Cliente")
                    <li>@Html.ActionLink("Funcionário", "Funcionario", "Funcionario")
                    <li>@Html.ActionLink("Lista de Funcionários", "ListarFuncionario", "Funcionario")
                    <li>@Html.ActionLink("Lista de Clientes", "ListarCliente", "Cliente")
                    <li>@Html.ActionLink("Lista de Jogos", "ListarJogo", "Jogo")
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Meu Aplicativo ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>